### ISSUE TITLE
RuntimeError: load_stbi: could not load <.

### ISSUE THREAD

**Issue by StanislavNikolov** [ml-explore/mlx-data#8] opened 2023-12-08 12:02 UTC
Here's a simple 7 line script based on the example in the readme, trying to load a single image from the [CelebA](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) dataset:

```python
import mlx.data as dx
dset = (
    dx.buffer_from_vector([{"image": "./000001.jpg"}])
    .to_stream()
    .load_image("image")
)
print(next(dset))
```

Here's the 000001.jpg from the dataset: https://0x0.st/H3TG.jpg

```sh
$ brew install libsndfile libsamplerate ffmpeg jpeg-turbo zlib bzip2 xz aws-sdk-cpp
$ python3 -m pip install mlx-data
$ python3 broken.py
```

# Expected result
```
{ "image": .... }
```

# Actual result 
```
Traceback (most recent call last):
  File "/Users/stjo/broken/broken.py", line 7, in <module>
    print(next(dset))
          ^^^^^^^^^^
RuntimeError: load_stbi: could not load <.
```
 
python version: Python 3.11.6
mlx-data version: 0.0.1

**Comment by StanislavNikolov** [comment] 2023-12-08 12:11
The reason this crashes is that the values in the dictionary passed to buffer_from_vector must be buffers.
Here's the fixed script:

```python
import mlx.data as dx
print(dx.__version__)
dset = (
    dx.buffer_from_vector([{"image": "./000001.jpg".encode("ascii")}])
    .to_stream()
    .load_image("image")
)
print(next(dset))
```

Notice the .encode("ascii").

I believe the exceptions thrown are not descriptive enough.
"load_stbi: could not load <." for not passing the paths properly is confusing.

**Comment by andresy** [comment] 2023-12-09 05:02
Thanks! Indeed, mlx.data expects bytes for int8 arrays. This will be clarified. In the above, you could have used `b"./000001.jpg"` too. Under the hood, the int8/char array is interpreted as the string path.

In that respect, note:
```
import mlx.data as dx
dset = (
    dx.buffer_from_vector([{"image": b"./000001.jpg"}])
    .to_stream()
#    .load_image("image")                                                                                                                                                                                      
)
sample = next(dset)
print(sample, sample["image"].tobytes())

# shows:
{'image': array([ 46,  47,  48,  48,  48,  48,  48,  49,  46, 106, 112, 103],
      dtype=int8)} b'./000001.jpg'
```

**Comment by angeloskath** [comment] 2023-12-15 19:20
I will close this since it is not a loading bug but we should indeed consider having a better error reporting.

The problem is the C++ side has no idea if you wanted to pass this unicode array or it was by accident and the error is could not load path `< <null terminated string here> >`.

A simple solution would be to check in `buffer_from_vector` whether one of the keys points to a string and emit a warning, something like `Did you forget to pass bytes?`.

**Closed by angeloskath** 2023-12-15 19:20 UTC
